application: toddhdow-mlb
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /L.N9BB1GIX8zQKqlffGu_8426epSQ1iB59pKk2EiDg--.html
  static_files: L.N9BB1GIX8zQKqlffGu_8426epSQ1iB59pKk2EiDg--.html
  upload: L.N9BB1GIX8zQKqlffGu_8426epSQ1iB59pKk2EiDg--.html

- url: /index\.html
  static_files: index.html
  upload: index\.html

- url: /.*
  script: hello.app

libraries:
- name: webapp2
  version: "2.5.1"
